### ISSUE TITLE
Nested breaks turn into goto/label

### ISSUE THREAD

**Issue by Aussiemon** [marsinator358/luajit-decompiler-v2#17]
This snippet
```
for i = 1, 2, 3 do
	if x then
		print("Then")
		if y then
			print ("Nested then")
		else
			break
		end
	else
		break
	end
end
```
becomes
```
for i = 1, 2, 3 do
	if x then
		print("Then")

		if y then
			print("Nested then")

			goto label_0_0
		end
	end

	do break end

	if false then
		break
	end

	::label_0_0::
end
```

Breaks converting to gotos is problematic when expecting Lua 5.1 output.

**Comment by marsinator358** [comment]
This is a side effect of the current simple decompilation logic for if statements.

I'm planning to improve this by trying to rebuild them without gotos first, but this will only work  
for blocks that don't contain real gotos because I can't think of an algorithm that finds a combination  
with the least amount of gotos left without needing to brute force it.

**Comment by marsinator358** [comment]
I've improved the decompilation logic, if the original code didn't have gotos the decompiled code should also not contain any.
