### ISSUE TITLE
Miscellaneous malformed output with edge cases

### ISSUE THREAD

**Issue by Aussiemon** [marsinator358/luajit-decompiler-v2#18]
The snippet
```
while x or true do
	print ("while x or true")
end
```
becomes
```
::label_0_1::

if not x then
	-- Nothing
end

repeat
	print("while x or true")

	goto label_0_1
until true
```
which is problematic for the same reason as #17.

Several more minor edge cases are:
```
if x or true then
	print("if or true")
end
```
becomes
```
if not x then
	-- Nothing
end

print("if or true")
```

And
```
if x == 0 then
	print ("then")
else	   
end
```
becomes
```
if x == 0 then
	print("then")
end

if false then
	-- Nothing
end
```

And
```
while true do
	if x then
		break
	end
end
```
becomes
```
repeat
	-- Nothing
until x
```

**Comment by Aussiemon** [comment]
I think that all of these are still technically equivalent, so it's nice to see that the output is still correct when malformed.

**Comment by marsinator358** [comment]
I'm going to include some special handling for the first case.

The second case however can't be fixed because these kind of conditions  
look exactly like empty if statements in the bytecode.  
I will implement special handling in the future that will prevent a decompilation failure or not correctly inlined code  
when they are part of an assignment that is part of a more complex statement or a table constructor though.

Third one won't be fixed because it's only a problem for empty else statements  
and a side effect of the logic required to properly support gotos.  

Last one is also a wontfix because that's how I detect repeat conditions (and I'm too lazy to change that).
