### ISSUE TITLE
Doubts about encoding (UTF-8 BOM)

### ISSUE THREAD

**Issue by IlluminatiWave** [marsinator358/luajit-decompiler-v2#28]
Is there a way to encode the lua in utf-8 without using BOM (Using BOM will cause lua to send the error message `C:\Program Files (x86)\Lua\5.1\lua.exe: .\luafile.lua:1: unexpected symbol near '´'` )

**Comment by marsinator358** [comment]
That's because you're supposed to run/recompile it with LuaJIT and not normal Lua.  
LuaJIT made some changes to 5.1 which can cause issues with the normal version  
(e.g. names accepting values beyond the ASCII range, special FFI types, gotos).

The BOM is needed for text editors to properly recognize the UTF-8 encoding.  
However, you can always use the `-u` option if you want to disable UTF-8.
