### ISSUE TITLE
Unable to decrypt .l64 files

### ISSUE THREAD

**Issue by ER-95** [marsinator358/luajit-decompiler-v2#54]
Hi,

I have a .l64 file I'm trying to decrypt, but it reports the below issue:
![image](https://github.com/user-attachments/assets/c4376be8-4f8d-41f1-9ceb-f2bd08a492af)

Is anyone able to help with this please? I've also attached the file in question (in a zip).
[ECSFS25.zip](https://github.com/user-attachments/files/17717778/ECSFS25.zip)

Many thanks

**Comment by marsinator358** [comment]
The bytecode files from farming simulator need to be decrypted first before they can be decompiled.  
Giants also seem to have switched away from using LuaJIT so this decompiler won't work.

**Comment by scfmod** [comment]
Yeah they have switched to Luau, unfortunately 🤦‍♂️
Such a pity considering your decompiler is really good :-) And I suspect the Luau bytecode is somewhat different logic wise as well, so guessing a lot of the code can't be re-tooled?

**Comment by marsinator358** [comment]
> And I suspect the Luau bytecode is somewhat different logic wise as well, so guessing a lot of the code can't be re-tooled?

I'm not familiar with Luau bytecode but the decompiler would definitely need to rewritten from scratch because  
of the Luau compiler optimisations. There are also already many free and paid Luau decompilers available that are still  
in active development so I don't think it's worth the effort to write a new one.
