### ISSUE TITLE
CLI features

### ISSUE THREAD

**Issue by scfmod** [marsinator358/luajit-decompiler-v2#6]
Thanks for creating this updated decompiler, it works a lot better than the old python one! :)

Would love to have some more features for using the decompiler as a CLI:
- Command argument for output folder
- Command option for filtering file extensions (i.e ".lua")
- Command option for logging assertion error to stdout instead of showing MessageBox

**Comment by marsinator358** [comment]
I'm not planning to implement command line options as I've specifically avoided them  
because it's just a one-shot tool and I've wanted to make it easy to use.

Maybe if the project becomes more popular and more people request it. If you want to skip  
assertion errors because of invalid files you can hold down enter as continue is auto selected.

**Comment by scfmod** [comment]
Thanks for reply, no worries!
I'll maybe look into creating a pull request to add optional CLI mode when I got time and the git/source zip is up to date.

**Comment by marsinator358** [comment]
I've implemented an optional CLI, let me know if you have problems or need more options.

**Comment by scfmod** [comment]
That's awesome! I'll try it out today
